name: mrcode
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Networking
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  pretty_dio_logger: ^1.3.1
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.6
  # for dependency injection
  get_it: ^7.7.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
   # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.10+1
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3
   # Flutter library to load and cache network images.
  cached_network_image: ^3.3.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.2.3
  # easy way to add shimmer effect
  shimmer: ^3.0.0
  # firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  #Flutter plugin for Google Sign-In
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
